# Generated by Django 5.2.6 on 2025-10-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_alter_employee_department'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='type',
            field=models.CharField(choices=[('leave', 'Leave'), ('attendance', 'Attendance'), ('overtime', 'Overtime'), ('late', 'Late'), ('working_hours', 'Working Hours'), ('others', 'Others')], db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['company', 'department', 'type'], name='company_pol_company_45bd6b_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['company', 'type'], name='company_pol_company_bf1f8a_idx'),
        ),
    ]
