# Generated by Django 5.2.1 on 2025-08-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_company_customuser_user_type_customuser_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='countryCode',
            field=models.CharField(default='+91', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='ownerName',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='isInitialPassword',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='size',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
