# Generated by Django 5.2.1 on 2025-08-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_company_countrycode_company_ownername_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='overtime_eligible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='working_hours',
            field=models.JSONField(default=dict),
        ),
    ]
