# Generated by Django 5.2.1 on 2025-08-30 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_employee_overtime_eligible_employee_working_hours'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='company.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='documents',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(choices=[('sales', 'Sales-Onfield'), ('office', 'In-Office')], db_index=True, max_length=10),
        ),
    ]
