# Generated by Django 5.2.6 on 2025-10-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_alter_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
