# Generated by Django 5.2.6 on 2025-10-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_employee_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(choices=[('sales', 'Sales-Onfield'), ('office', 'In-Office')], db_index=True, max_length=30),
        ),
    ]
