# Generated by Django 5.2.6 on 2025-10-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0011_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Company Admin'), ('employee', 'Employee')], default='employee', max_length=30),
        ),
    ]
